env:
  global:
    - CC_TEST_REPORTER_ID=abf0a371ff8851f13b563671914b195bb46f0997f0f93142e666d9acad08e22f

language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem update bundler

install:
  - bundle install --jobs=3 --retry=3
  - if [[ ! `ruby --version` =~ ^ruby\ 2\.1 ]]; then gem install rubocop; fi

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - if [[ ! `ruby --version` =~ ^ruby\ 2\.1 ]]; then rubocop; fi
  - bundle exec rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
